# Generated by Django 3.2.12 on 2022-02-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_length', models.CharField(blank=True, choices=[('1', '1hr Session'), ('2', '2hr Session'), ('3', '3hr Session'), ('4', '4hr Session')], max_length=255)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('date_time', models.DateTimeField(blank=True, max_length=255)),
            ],
        ),
    ]
